apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginmedicure-appx
  template:
    metadata:
      labels:
        app: medicure-app
    spec:
      containers:
      - name: medicure-app
        image: nikitaks997797/capstone_project2:$BUILD_NUMBER
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: docker_private